<h3><?php echo  $US['nav-config']?></h3>
<a target="content" onclick="h(this);" href="aconfig.php"><?php echo  $US['nav-aconfig']?></a>
<a target="content" onclick="h(this);" href="pconfig.php"><?php echo  $US['nav-pconfig']?></a>
<a target="content" onclick="h(this);" href="vhost.php"><?php echo  $US['nav-vhost']?></a>
<a target="content" onclick="h(this);" href="apsetup.php"><?php echo  $US['nav-apsetup']?></a>
<a target="content" onclick="h(this);" href="psetup.php"><?php echo  $US['nav-psetup']?></a>
<a target="content" onclick="h(this);" href="sslpsetup.php"><?php echo  $US['nav-sslpsetup']?></a>
<a target="content" onclick="h(this);" href="mqsetup.php"><?php echo  $US['nav-mqsetup']?></a>