<h3><a href="javascript:unhide('03');"><?php echo  $US['nav-docs1']?></a></h3>
<div id="03" class="hidden"><a target="_sdoc" onclick="h(this);" href="/docs/"><?php echo  $US['nav-sdoc']?></a></div>
<h3><a href="javascript:unhide('04');"><?php echo  $US['nav-docs2']?></a></h3>
<div id="04" class="hidden"><a target="_uguide" onclick="h(this);" href="http://doc.uniformserver.com"><?php echo  $US['nav-udoc']?></a>
<a target="_ucenter" onclick="h(this);" href="http://wiki.uniformserver.com/index.php/Main_Page"><?php echo  $US['nav-wiki']?></a>
<a target="_php" onclick="h(this);" href="http://www.php.net/download-docs.php"><?php echo  $US['nav-phdoc']?></a>
<a target="_mysql" onclick="h(this);" href="http://www.mysql.com/documentation/"><?php echo  $US['nav-mydoc']?></a>
<a target="_perl" onclick="h(this);" href="http://www.ayni.com/perldoc/"><?php echo  $US['nav-pedoc']?></a></div>