<?php
/**
 * SpamReferer module
 *
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting source code
 * which is considered copyrighted (c) material of the original comment or credit authors.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * @copyright	The XOOPS Project http://sourceforge.net/projects/xoops/
 * @license             http://www.fsf.org/copyleft/gpl.html GNU public license
 * @package	SpamReferer
 * @since		2.3.0
 * @author 	kris <http://www.xoofoo.org>
 * @version	$Id$
**/

define("_AM_SPAMREFERER_MANAGER_INDEX",                  "Index");
define("_AM_SPAMREFERER_MANAGER_ABOUT",                  "About");
define("_AM_SPAMREFERER_MANAGER_HELP",                  "Help");
define("_AM_SPAMREFERER_MANAGER_PREFERENCES",            "Settings");
define("_AM_SPAMREFERER_MANAGER_UPDATE",                 "Update");

define("_AM_SPAMREFERER_MANAGER_FOOTER",                 "<div class='right smallsmall italic pad10'>SpamReferer for XOOPS is maintened by <a class='tooltip' rel='external' href='http://labs.XooFoo.org' title='VisitXooFoo Laboratory>Labs.XooFoo.org</a></div>");

// Index.php
define("_AM_SPAMREFERER_MANAGER_INDEX_TXT1" , "
<h4>Secure your site a bit more</h4>
<p>A scourge on the web that any webmaster is not always linked with the consumption of bandwidth by referents that link links to your website.</p>
<p>This tends to several objectives:</p>
<ul>
<li>try to get a backlink for example generated by a statistics module open to everyone (not to obviously)</li>
<li>spammer trying to come to your website (forum, guestbook, blog, ...)</li>
</ul>
<p>Referer Spam mode is ideal for effective struggle against this scourge.</p>
");

// About.php
define("_AM_SPAMREFERER_ABOUT_RELEASEDATE",        "Update date");
define("_AM_SPAMREFERER_ABOUT_AUTHOR",                   "Author");
define("_AM_SPAMREFERER_ABOUT_CREDITS",                  "Credits");
//define("_AM_SPAMREFERER_ABOUT_README",                   "General Infos");
//define("_AM_SPAMREFERER_ABOUT_MANUAL",               "Help");
define("_AM_SPAMREFERER_ABOUT_LICENSE",                  "License");
define("_AM_SPAMREFERER_ABOUT_MODULE_STATUS",            "Status");
define("_AM_SPAMREFERER_ABOUT_WEBSITE",                  "Website");
define("_AM_SPAMREFERER_ABOUT_AUTHOR_NAME",              "Author name");
//define("_AM_SPAMREFERER_ABOUT_AUTHOR_WORD",              "Author words");
define("_AM_SPAMREFERER_ABOUT_CHANGELOG",                "Change Log");
define("_AM_SPAMREFERER_ABOUT_MODULE_INFO",              "Module Infos");
define("_AM_SPAMREFERER_ABOUT_AUTHOR_INFO",              "Author Infos");
//define("_AM_SPAMREFERER_ABOUT_DISCLAIMER",               "Disclaimer");

?>