<h3><a href="javascript:unhide('06');"><?php echo  $US['nav-plugins']?></a></h3>
<div id="06" class="hidden"><a target="_pear" onclick="h(this);" href="<?php echo $apanel?>/plugins/pear/go_pear.php"><?php echo  $US['nav-pear']?></a>
<a target="content" onclick="h(this);" href="plugins/eaccelerator/control.php"><?php echo  $US['nav-eaccelerator']?></a>
<a target="content" onclick="h(this);" href="keycert.php"><?php echo  $US['nav-key']?></a>
<a target="content" onclick="h(this);" href="mysqlrestore.php"><?php echo  $US['nav-mysqlrestore']?></a></div>



