<?php
// $Id$
//  ------------------------------------------------------------------------ //
//  Author: Andrew Mills                                                     //
//  Email:  ajmills@sirium.net                                               //
//	About:  This file is part of the AM Reviews module for Xoops v2.         //
//                                                                           //
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //

// Any copyright notice, instructions, etc...
$modversion['name']			= _MI_AM_HTERROR_NAME;
$modversion['version']		= 0.06;
$modversion['description']	= _MI_AM_HTERROR_DESC;
$modversion['credits']		= '';
$modversion['author']		= 'Andrew Mills - http://support.sirium.net';
$modversion['help']			= 'help.html';
$modversion['license']		= 'GPL see LICENSE';
$modversion['official']		= 0;
$modversion['image']		= 'images/amhterror_slogo.png';
$modversion['dirname']		= 'amhterror';

// Admin
$modversion['hasAdmin']		= 1;
$modversion['adminindex']	= "admin/index.php";
$modversion['adminmenu']	= "admin/menu.php";

// Menu
$modversion['hasMain'] = 0;

// Templates
$modversion['templates'][1]['file'] 		= "amhterror_index.html"; // main index - default view
$modversion['templates'][1]['description'] 	= "";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql']		= "sql/mysql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0]	= "amhterror_errors";
$modversion['tables'][1]	= "amhterror_msgs";

// Config options
// Ignore error reports for admins.
$key = 1;
$modversion['config'][$key]['name']			= 'ignoreadmin';
$modversion['config'][$key]['title']		= '_MI_AMHTERR_IGNOREADMIN';
$modversion['config'][$key]['description']	= '_MI_AMHTERR_IGNOREADMINDSC';
$modversion['config'][$key]['formtype']		= 'yesno';
$modversion['config'][$key]['valuetype']	= 'int';
$modversion['config'][$key]['default']		= 1;

// option to turn off error reporting
$key++;
$modversion['config'][$key]['name']			= 'errorreporting';
$modversion['config'][$key]['title']		= '_MI_AMHTERR_REPORTING';
$modversion['config'][$key]['description']	= '_MI_AMHTERR_REPORTINGDSC';
$modversion['config'][$key]['formtype']		= 'yesno';
$modversion['config'][$key]['valuetype']	= 'int';
$modversion['config'][$key]['default']		= 0;

// option to turn on auto line breaks
$key++;
$modversion['config'][$key]['name']			= 'linebreaks';
$modversion['config'][$key]['title']		= '_MI_AMHTERR_LINEBRKS';
$modversion['config'][$key]['description']	= '_MI_AMHTERR_LINEBRKSDSC';
$modversion['config'][$key]['formtype']		= 'yesno';
$modversion['config'][$key]['valuetype']	= 'int';
$modversion['config'][$key]['default']		= 0;

$key++;
// Show title in page title
$modversion['config'][$key]['name']			= 'titleaspagetitle';
$modversion['config'][$key]['title']		= '_MI_AMHTERR_PAGETTL';
$modversion['config'][$key]['description']	= '_MI_AMHTERR_PAGETTLDSC';
$modversion['config'][$key]['formtype']		= 'select';
$modversion['config'][$key]['valuetype']	= 'int';
$modversion['config'][$key]['default']		= '1';
$modversion['config'][$key]['options']		= array('_MI_AMHTERR_PAGETTL1' => '0', '_MI_AMHTERR_PAGETTL2' => '1', '_MI_AMHTERR_PAGETTL3' => '2');

// Date format - day separator
$key++;
$modversion['config'][$key]['name']			= 'dateformat';
$modversion['config'][$key]['title']		= '_MI_AMHTERR_DATEFRMT';
$modversion['config'][$key]['description']	= '_MI_AMHTERR_DATEFRMTDSC';
$modversion['config'][$key]['formtype']		= 'textbox';
$modversion['config'][$key]['valuetype']	= 'text';
$modversion['config'][$key]['default']		= 'd/m/Y';

// Date format - day separator
$key++;
$modversion['config'][$key]['name']			= 'numreports';
$modversion['config'][$key]['title']		= '_MI_AMHTERR_NUMREPS';
$modversion['config'][$key]['description']	= '_MI_AMHTERR_NUMREPSDSC';
$modversion['config'][$key]['formtype']		= 'textbox';
$modversion['config'][$key]['valuetype']	= 'int';
$modversion['config'][$key]['default']		= '50';

$key++;
#$modversion['config'][1]['name']		= 'indextype';
#$modversion['config'][1]['title']		= '_MI_AMHTERR_OTPN_INDEX';
#$modversion['config'][1]['description']	= '_MI_AMHTERR_OTPN_INDEXDESC';
#$modversion['config'][1]['formtype']	= 'select';
#$modversion['config'][1]['valuetype']	= 'int';
#$modversion['config'][1]['default']		= '0';
#$modversion['config'][1]['options']		= array('default' => '0', 'Directory' => '1');

?>
