<?php
/**
 * Oups Module
 *
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting source code
 * which is considered copyrighted (c) material of the original comment or credit authors.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * @copyright        The XOOPS Project http://sourceforge.net/projects/xoops/
 * @license             http://www.fsf.org/copyleft/gpl.html GNU public license
 * @package         Oups Module
 * @since		2.5.0
 * @author            Andrew Mills <ajmills@sirius.net>
 * @version            $Id $
**/

// Any copyright notice, instructions, etc...
$modversion['name']		= _MI_AM_OUPS_NAME;
$modversion['version']		= 1.0;
$modversion['description']	= _MI_AM_OUPS_DESC;
$modversion['credits']		= '';
$modversion['author']		= 'Andrew Mills - http://support.sirium.net';
$modversion['help']		= 'help.html';
$modversion['license']		= 'GPL see LICENSE';
$modversion['official']		= 0;
$modversion['image']		= 'images/oups_slogo.png';
$modversion['dirname']	= 'oups';

// Admin
$modversion['hasAdmin']		= 1;
$modversion['adminindex']	= "admin/index.php";
$modversion['adminmenu']	= "admin/menu.php";

// Menu
$modversion['hasMain'] = 1;

// Search option
$modversion['hasSearch'] = 0;

// Templates
$modversion['templates'][1]['file'] 		= "oups_index.html"; // main index - default view
$modversion['templates'][1]['description'] 	= "";
$modversion['templates'][2]['file'] 		= "oups_searchform.html"; // searchform - default view
$modversion['templates'][2]['description'] 	= "";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql']		= "sql/mysql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0]	= "oups_errors";
$modversion['tables'][1]	= "oups_msgs";

// Config options
// Ignore error reports for admins.
$key = 1;
$modversion['config'][$key]['name']		= 'ignoreadmin';
$modversion['config'][$key]['title']			= '_MI_OUPS_IGNOREADMIN';
$modversion['config'][$key]['description']	= '_MI_OUPS_IGNOREADMINDSC';
$modversion['config'][$key]['formtype']		= 'yesno';
$modversion['config'][$key]['valuetype']		= 'int';
$modversion['config'][$key]['default']		= 1;

// option to turn off error reporting
$key++;
$modversion['config'][$key]['name']		= 'errorreporting';
$modversion['config'][$key]['title']			= '_MI_OUPS_REPORTING';
$modversion['config'][$key]['description']	= '_MI_OUPS_REPORTINGDSC';
$modversion['config'][$key]['formtype']		= 'yesno';
$modversion['config'][$key]['valuetype']		= 'int';
$modversion['config'][$key]['default']		= 0;

// option to turn on auto line breaks
$key++;
$modversion['config'][$key]['name']		= 'linebreaks';
$modversion['config'][$key]['title']			= '_MI_OUPS_LINEBRKS';
$modversion['config'][$key]['description']	= '_MI_OUPS_LINEBRKSDSC';
$modversion['config'][$key]['formtype']		= 'yesno';
$modversion['config'][$key]['valuetype']		= 'int';
$modversion['config'][$key]['default']		= 0;

$key++;
// Show title in page title
$modversion['config'][$key]['name']		= 'titleaspagetitle';
$modversion['config'][$key]['title']			= '_MI_OUPS_PAGETTL';
$modversion['config'][$key]['description']	= '_MI_OUPS_PAGETTLDSC';
$modversion['config'][$key]['formtype']		= 'select';
$modversion['config'][$key]['valuetype']		= 'int';
$modversion['config'][$key]['default']		= '1';
$modversion['config'][$key]['options']		= array('_MI_OUPS_PAGETTL1' => '0', '_MI_OUPS_PAGETTL2' => '1', '_MI_OUPS_PAGETTL3' => '2');

// Date format - day separator
$key++;
$modversion['config'][$key]['name']		= 'dateformat';
$modversion['config'][$key]['title']			= '_MI_OUPS_DATEFRMT';
$modversion['config'][$key]['description']	= '_MI_OUPS_DATEFRMTDSC';
$modversion['config'][$key]['formtype']		= 'textbox';
$modversion['config'][$key]['valuetype']		= 'text';
$modversion['config'][$key]['default']		= 'd/m/Y';

// Date format - day separator
$key++;
$modversion['config'][$key]['name']		= 'numreports';
$modversion['config'][$key]['title']			= '_MI_OUPS_NUMREPS';
$modversion['config'][$key]['description']	= '_MI_OUPS_NUMREPSDSC';
$modversion['config'][$key]['formtype']		= 'textbox';
$modversion['config'][$key]['valuetype']		= 'int';
$modversion['config'][$key]['default']		= '50';

xoops_load('XoopsEditorHandler');
$editor_handler = XoopsEditorHandler::getInstance();
?>
